cory2067/gtsosu

- client/src/content/igts_2021-en.js
Should be the last time hopefully
> Fixing IGTS rules again

- client/src/content/igts_2021-en.js
> Another rule fix

- client/src/components/modules/AddPlayerModal.js
- client/src/components/modules/Qualifiers.js
- client/src/components/pages/Players.js
- server/api.js
> add feature for admins to add referee/players to qualifier lobbies

- client/src/components/modules/AddMapModal.js
- client/src/components/modules/MapCard.css
- client/src/components/modules/MapCard.js
- client/src/public/custom-map-badge.svg
- client/src/public/custom-song-badge.svg
- server/models/map.js
Also added switches when adding map to mark the relevant fields.
> Add custom map and song badge

- README.md
- client/src/components/modules/Navbar.js
- server/api.js
- Migrates navbar code to react hooks
- Adds a new api route that fetches what languages are available for the given tournament
- Populates the language dropdown based on which languages are available for the tourney, instead of being hardcoded 
Closes #38
> Populate language dropdown based on available languages

- client/src/components/pages/TourneyStaff.js
> Refactor tourneystaff

- client/src/components/pages/Stats.js
(for team tourneys only for now)
> add button to export quals stats to json for lazer tourney client

- server/permissions/UserAuth.ts
Also fixed a critical permission mistake where hasSuperRole is always true, due to the calls to hasRole not being awaited
> UserAuth now allows undefined user

- client/src/components/modules/Qualifiers.js
- client/src/components/pages/Schedule.js
- client/src/components/pages/Stats.js
- qualifier lobby mp link becomes publically visible when stage stats visibility is enabled
- fix tables not showing when StageStats is undefined
- json generator works for non-team tourneys
- ran prettier again
> some small changes/fixes

- server/api.ts
- server/api/map.ts
- server/auth.ts
- server/db.ts
- server/permissions/UserAuth.ts
- server/permissions/contexts/MatchContext.ts
- server/server.ts
- server/types.ts
- server/util.ts
- tsconfig.json
Help sort out when things are undefined (like req.user)
> Add strict null checks to backend ts

- client/src/components/pages/Stats.js
> fix decimal places and seed size calculation

- client/src/components/pages/Schedule.js
- server/api.ts
- server/permissions/UserAuth.ts
- server/permissions/contexts/TeamContext.ts
Can't reproduce on dev server, added tourney field to submit and delete warmup requests for now
> Warmup submission fix

- server/api.ts
~~i made it a side effect instead of really validating the mp link. i don't really have a strong opinion on which one is better, i just happened to write it this way first :pehpehga:~~ nvm I changed it
> store stage stats for bracket stages

- server/ensure.ts
Reverts cory2067/gtsosu#96
Website went down
> Revert "Migrate ensure"

- client/src/components/modules/SubmitResultsModal.js
- client/src/components/pages/Schedule.js
- client/src/components/pages/Stats.js
- server/api.ts
- server/models/match.ts
- server/tests/permission.test.ts
> add bans to matches

- client/src/components/pages/Stats.css
- client/src/components/pages/Stats.js
> added beatmap info and ban count to stats table headers

- client/src/components/modules/TourneyCard.css
- client/src/components/modules/TourneyCard.js
- client/src/components/pages/Home.css
- client/src/content/home-en.js
Implement tourney cards redesign as show in this [figma](https://www.figma.com/file/LjowYzqzpvMPgphtNDjXjU/Redesign-Attempt-(free-ver.)?node-id=2%3A2)
> Tourney card redesign

- client/src/components/pages/TourneyStaff.css
- client/src/components/pages/TourneyStaff.js
- client/src/utilities.js
This is implemented purely on client's side for now, might want to consider a more robust structure to define if a given role is staff or helper in the future.
> Implement staff and helper csv export

- client/src/components/pages/Players.js
- client/src/components/pages/Stats.js
- server/api.ts
- changed POST /api/player-stats to take an array of players stats to update
- bonus: fixed addPlayerScore not working if there are no stats for the map yet
- note: not implemented for teams yet
> add function to assign player seeds from qualifier stats

- client/src/components/pages/Stats.js
- server/api.ts
- server/models/stage-stats.ts
> store mods used, and show it in FM map stats. also added seed tooltip

- client/src/components/pages/Players.js
One thing to note is that the threshold values for eligibility is hard coded in the front end here
> Potential team counter for country based team tournies

- client/src/components/pages/Players.js
- client/src/components/pages/Stats.js
- server/api.ts
(it's mostly the same as the previous PR [#129](https://github.com/cory2067/gtsosu/pull/129))
- changed POST /api/team-stats to take an array of team stats to update
> assign team seeds from qualifier stats

- client/src/components/pages/TourneyStaff.js
- server/api.ts
Resolves #48, some of the diff seem to be prettier auto formatting.
> Implement multi-role assignment

- client/src/components/modules/CreateTeamModal.js
- client/src/components/modules/EditTourneyModal.js
- client/src/components/pages/NewTourneyHome.js
- client/src/components/pages/Players.js
- server/api.ts
- server/models/tournament.ts
adding a property to tournament model so that the team size can be edited, and the modal for registering/editing team will show that number of player slots
> added Tournament.maxTeamSize

- client/src/components/modules/EditTourneyModal.js
- client/src/components/pages/NewTourneyHome.js
- server/api.ts
- server/models/tournament.ts
> added required countries to tournament settings

- client/src/components/pages/NewTourneyHome.js
- client/src/content/ui.js
(only appears when content.submissions is not empty)
(for MGTS in particular)
> added "Entry Submissions" button

- client/src/components/modules/UserModal.js
> fixed custom bg options not showing up

- client/src/components/pages/Players.js
Just a quick frontend implementation, shouldn't affect anything else
~~handleTeamExport is mostly written by copilot~~
> Implement team list export

- client/src/components/App.js
- client/src/components/modules/MapCard.js
- client/src/components/modules/Navbar.js
- client/src/components/pages/Songs.js
- client/src/content/ui.js
- server/api.ts
mvp (minimum viable product) because we don't have any design ideas right now ![trol](https://cdn.discordapp.com/emojis/1011036088246206494.webp?size=24&quality=lossless)
> custom songs page

- client/src/components/pages/Schedule.js
- server/api.ts
> added admin feature to edit match details

- server/api.ts
- server/permissions/UserRole.ts
Also updated `canViewHiddenPools` and `cantPlay` to use `UserAuth`
> Forbid playtester from joining a tourney

- client/src/components/App.js
- client/src/components/App.less
- client/src/components/modules/Navbar.js
- client/src/components/pages/AllStaff.css
- client/src/components/pages/AllStaff.js
- server/api.ts
> Add page for all GTS staff

- client/src/components/modules/EditTourneyModal.js
- client/src/components/pages/NewTourneyHome.js
- package-lock.json
- package.json
- server/api.ts
- server/models/tournament.ts
- server/server.ts
how this works:
- added yet another tournament setting. Specify a Discord server ID to enforce membership when registering to the tournament
- the backend now logs in to the DIscord bot on startup. It will be used to check membership when registering
- if the user hasn't linked their Discord account, an error will be returned saying so
- if the user's Discord account was not found to be a member of the Discord server, a different error will be returned
- if some other error is encountered in the process, it'll return an error message saying to contact staff
> discord server membership check

- client/src/components/modules/EditTourneyModal.js
- client/src/components/pages/NewTourneyHome.js
- package-lock.json
- package.json
- server/api.ts
- server/models/tournament.ts
- server/server.ts
> Revert "discord server membership check"

- client/src/components/modules/EditTourneyModal.js
- client/src/components/pages/NewTourneyHome.js
- package-lock.json
- package.json
- server/api.ts
- server/models/tournament.ts
- server/server.ts
> Revert "Revert "discord server membership check""

- server/api.ts
- server/types.ts
- server/util.ts
One thing to note is that the `legacyGamemodeId` map is defined in `types.ts`, not 100% sure if it fits there
> Warmup submission for different game modes

- client/src/auth.ts
- client/src/components/App.tsx
- client/src/components/RouteWrappers.tsx
- client/src/components/modules/LoginButton.css
- client/src/components/modules/LoginButton.js
- client/src/components/modules/Navbar/Right/Compact/LoginMenuItem.tsx
- client/src/components/modules/Navbar/Right/Regular/LoginButton.css
- client/src/components/modules/Navbar/Right/Regular/LoginButton.tsx
- client/src/components/modules/Navbar/Right/Regular/NavbarRightRegular.tsx
- client/src/components/modules/UserModal.js
- client/src/components/pages/TourneyHome.js
- client/src/utilities.js
rip funny shaking login button
now, when you click on the "login to register" button, it'll actually open up the login window, and then automatically open up the registration confirmation when you log in
> Make register button open up login popup

- client/src/components/modules/TeamCard.css
- client/src/components/modules/UserCard.css
- client/src/components/modules/UserCard.js
- client/src/components/pages/Stats.js
from [tanza's figma](https://www.figma.com/file/7oTWmsv1NLkMCKE0BsbD2t/GTS-Web)
still missing a few things so this is sorta tentative and subject to change
- missing the new heart icon
- team card didn't have an actual design yet so I just did my own thing
> updated player card design

- client/src/components/modules/EditTourneyModal.js
- client/src/components/pages/Schedule.js
- client/src/components/pages/TourneyHome.js
- server/api.ts
- server/models/tournament.ts
- server/server.ts
(sneaking in a payload limit increase to fix the issue of not being able to edit stage stats since the egts 2025 qualifiers stats were 122kb)
> add tourney setting to disable warmups
